- .gitignore
- .travis.yml
- README.md
- galaxy.yml
- plugins/module_utils/netbox_dcim.py
- plugins/module_utils/netbox_ipam.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_device.py
- plugins/modules/netbox_interface.py
- plugins/modules/netbox_ip_address.py
- plugins/modules/netbox_prefix.py
- plugins/modules/netbox_site.py
- tests/unit/module_utils/test_netbox_base_class.py
This contains the modules and module_utils but isn't complete due to collections being new, but will update as collections matures
This includes travis-ci and tests are passing as well
> Added travis-ci integration

- .travis.yml
- README.md
- galaxy.yml
- plugins/module_utils/netbox_ipam.py
- plugins/modules/netbox_device_interface.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
This PR adds integration testing into the collection.  It also has some bug fixes for the netbox_ipam to work properly that the integration testing discovered
> Add integration testing

- README.md
- plugins/module_utils/netbox_ipam.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_aggregate.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
- tests/unit/module_utils/test_netbox_base_class.py
Fixes #14 
Omitting netbox_services as it needs more work and it isn't behaving as intended when specifying IP addresses. Will look into in the future
> Added netbox_aggregate

- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_device.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
- tests/unit/module_utils/test_netbox_base_class.py
> Added primary_ip4/6 to netbox_device, added tests, updated netbox_utils

- .travis.yml
- plugins/lookup/netbox.py
- tests/integration/integration-tests.yml
A first attempt to include my Netbox lookup plugin. I've attempted to write some integration tests and they appear to pass when I use a similarly configured Netbox container.
> Added netbox lookup plugin (#26)

- .travis.yml
Integration testing on Netbox v2.5 is broken due new startup scripts. Using my own fork for v2.5 at the moment, but have PR in to fix
> Fix testing

- .travis.yml
- CHANGELOG.md
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_aggregate.py
- plugins/modules/netbox_device.py
- plugins/modules/netbox_device_bay.py
- plugins/modules/netbox_device_interface.py
- plugins/modules/netbox_device_role.py
- plugins/modules/netbox_device_type.py
- plugins/modules/netbox_inventory_item.py
- plugins/modules/netbox_ip_address.py
- plugins/modules/netbox_ipam_role.py
- plugins/modules/netbox_manufacturer.py
- plugins/modules/netbox_platform.py
- plugins/modules/netbox_prefix.py
- plugins/modules/netbox_rack.py
- plugins/modules/netbox_rack_group.py
- plugins/modules/netbox_rack_role.py
- plugins/modules/netbox_region.py
- plugins/modules/netbox_rir.py
- plugins/modules/netbox_site.py
- plugins/modules/netbox_tenant.py
- plugins/modules/netbox_tenant_group.py
- plugins/modules/netbox_vlan.py
- plugins/modules/netbox_vlan_group.py
- plugins/modules/netbox_vrf.py
- tests/integration/integration-tests.yml
This fixes #24 
Errors now cause the task to fail if the required fields aren't specified.
This is using a mix of `required_if` and just the return from Netbox API.
> Added required_if to modules and module_utils

- plugins/lookup/netbox.py
- tests/integration/integration-tests.yml
This fixes #31 and adds filter support.
> this adds filter API support to the lookup plugin.

- plugins/lookup/netbox.py
it's using the wrong path for virtual_machine - from dcim to virtualization.
> fix lookup plugin

- README.md
- plugins/module_utils/netbox_circuits.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_circuit.py
- plugins/modules/netbox_circuit_termination.py
- plugins/modules/netbox_circuit_type.py
- plugins/modules/netbox_provider.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
- tests/unit/module_utils/test_netbox_base_class.py
Add all circuit modules
Fixes #17
> new circuit modules

- CHANGELOG.md
- plugins/module_utils/netbox_utils.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
- tests/unit/module_utils/test_netbox_base_class.py
Added `virtual_machine` to the **ALLOWED_QUERY_PARAMS** for interfaces.
Added tests to account for this bug and test to make sure we don't regress to it.
Fixes #40
> Fixes issue with multiple results when attempting to create vm intfs

- .travis.yml
- galaxy.yml
- plugins/lookup/netbox.py
> Bug: netbox lookup: Error handling for invalid key file

- plugins/inventory/netbox.py
Pulled the Inventory Plugin netbox.py from ansible/ansible:devel and updated names to reflect collections namespacing so it works. All existing functionality has been manually tested on Ansible 2.9.1 and 2.9.2
> Netbox Inventory Plugin

- plugins/module_utils/netbox_utils.py
- tests/integration/integration-tests.yml
Fixes #73 
Removed **name** from search for manufacturer and added tests to make sure update works for manufacturers
> BugFix: Allow name updates to manufacturers

- .travis.yml
- README.md
- plugins/module_utils/netbox_circuits.py
- plugins/module_utils/netbox_dcim.py
- plugins/module_utils/netbox_extras.py
- plugins/module_utils/netbox_ipam.py
- plugins/module_utils/netbox_secrets.py
- plugins/module_utils/netbox_tenancy.py
- plugins/module_utils/netbox_utils.py
- plugins/module_utils/netbox_virtualization.py
- tests/integration/regression-tests.yml
Fixes #69 
This tests the connection to Netbox and fails if the request fails.
> BugFix: Fix connection error handling to Netbox

- plugins/module_utils/netbox_utils.py
- tests/integration/integration-tests.yml
> BugFix: Fix lag to be resolved without being a dictionary

- plugins/modules/netbox_ip_address.py
- tests/integration/integration-tests.yml
Added dns_name to netbox_ip_address and associated test
Fixes #84
> Feature: Added dns_name to arg_spec and documents for netbox_ip_address

- plugins/inventory/netbox.py
> Feature: Added region and region_id to ALLOWED_DEVICE_QUERY_PARAMETERS

- plugins/inventory/netbox.py
> Inventory-feature: Change lookups to property

- LICENSE
- galaxy.yml
Fixes #102 
Updated LICENSE for GPLv3.0+
Updated galaxy.yml to reflect the license for it is what is in the license file
> Documentation: Update Licenses

- plugins/inventory/netbox.py
Fixes #63 
This should remove the call to either the device or virtual machine endpoint if an query_filter is provided but is not valid. If multiple are set, it should only add the correct ones and then call with the correct filters.
> Inventory-bug: Added logic to not pull devices/vms if query_filters are not valid

- plugins/module_utils/netbox_dcim.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
> BugFix: Add intf to device in virtual chassis

- .travis.yml
- galaxy.yml
- plugins/module_utils/netbox_dcim.py
Fixes #114 
This was due to attempting to find a device on the wrong endpoint ("interfaces", instead of "devices").
Fixed that with static nb search on `nb.dcim.devices.get`
> BugFix: Incorrect search for device in netbox_dcim util

- CHANGELOG.md
> Update changelog - v0.1.8

- README.md
Fixed a typo and consistency of use of NetBox vs Netbox
> Minor changes for typos/usage

- plugins/module_utils/netbox_dcim.py
- plugins/modules/netbox_device_interface.py
- tests/integration/integration-tests.yml
- tests/integration/netbox-deploy.py
Fixes #105 
The original attempt at fixing it was nulling out `self.object` instead of `self.nb_object`. I believe this should resolve the issue
> BugFix: VC intf fix

- plugins/inventory/nb_inventory.py
> Enhancement - inventory plugin: Changed ip-addresses key to ip_addresses

- plugins/inventory/nb_inventory.py
> Inventory: Extract custom fields as host_vars

- plugins/modules/netbox_rack.py
- tests/integration/integration-tests.yml
- tests/integration/v2.6/tasks/netbox_rack.yml
- tests/integration/v2.7/tasks/netbox_rack.yml
This fixes #167 and adds a new rack width choice (10 inches) introduced in NetBox 2.7.9 (https://github.com/netbox-community/netbox/issues/4305).
> Update rack width to comply with latest API documentation

- plugins/modules/netbox_virtual_machine.py
> Enhancement: Added custom fields as option for netbox_virtual_machine

- plugins/module_utils/netbox_utils.py
- tests/integration/v2.6/tasks/netbox_service.yml
- tests/integration/v2.7/tasks/netbox_service.yml
- tests/integration/v2.8/tasks/netbox_service.yml
> Bugfix: Fix netbox_service to create new service with different protocols

- plugins/lookup/nb_lookup.py
> Allows lookup plugin to use a netbox configured for anonymous-readonly

- plugins/modules/netbox_rack.py
This fixes #189 by adding an entry for 21 inch racks in the choices for rack width.
> add option for 21 inch (ETSI) racks

- hacking/update_test_inventories.sh
- plugins/inventory/nb_inventory.py
- tests/integration/netbox-deploy.py
- tests/integration/targets/inventory/files/test-inventory-legacy.json
- tests/integration/targets/inventory/files/test-inventory-options.json
- tests/integration/targets/inventory/files/test-inventory-options.yml
- tests/integration/targets/inventory/files/test-inventory-plurals.json
- tests/integration/targets/inventory/files/test-inventory-plurals.yml
- tests/integration/targets/inventory/files/test-inventory.json
- tests/integration/targets/inventory/files/test-inventory.yml
> Inventory: add group_by options for cluster, cluster_type, and cluster_group

- plugins/inventory/nb_inventory.py
- tests/integration/targets/inventory/files/test-inventory-options-flatten.json
- tests/integration/targets/inventory/files/test-inventory-options-flatten.yml
- tests/integration/targets/inventory/files/test-inventory-plurals-flatten.json
- tests/integration/targets/inventory/files/test-inventory-plurals-flatten.yml
> Inventory: Implement flatten_config_context and flatten_custom_fields options

- plugins/modules/netbox_virtual_machine.py
the virtual machines API has no rack support.
> virtual_machines API has no rack support.

- CHANGELOG.md
Added CHANGELOG to release v0.2.2
> Updated CHANGELOG for v0.2.2

- README.md
Modify example to fix syntax error on example playbook.
> update example to fix syntax error fix #226

- plugins/modules/netbox_cluster.py
- tests/integration/targets/latest/tasks/netbox_cluster.yml
Replaces # 219 to add testing.
Removed the tenant from the query as #222 will resolve that issue and give users control.
> Enhancement: netbox_cluster - Adds tenant option

- plugins/module_utils/netbox_ipam.py
- tests/integration/targets/regression/tasks/main.yml
> Fixed check_mode for netbox_prefix and added necessary tests

- .travis.yml
- plugins/module_utils/netbox_utils.py
- tests/integration/targets/latest/tasks/netbox_power_outlet.yml
- tests/integration/targets/latest/tasks/netbox_power_port.yml
- tests/integration/targets/regression/tasks/main.yml
Fixes #242 
Also sets pynetbox to version 4.3.3 due to some breaking changes in 5.0.0
> Bugfix: Change tag diff to sets to assert uniqueness

- plugins/module_utils/netbox_utils.py
- tests/integration/targets/latest/tasks/netbox_circuit.yml
- tests/integration/targets/regression/tasks/main.yml
- tests/unit/module_utils/test_data/normalize_data/data.json
> Bugfix: Normalize descriptions to remove any extra whitespaces

- plugins/lookup/nb_lookup.py
- tests/integration/targets/latest/tasks/netbox_lookup.yml
> Enhancement: Allow OR operations in api_filters for nb_lookup

- plugins/module_utils/netbox_utils.py
- tests/unit/module_utils/test_data/normalize_data/data.json
> Bugfix: Normalize MAC address to match NetBox

- plugins/module_utils/netbox_utils.py
> rear_port should be rear_ports

- plugins/inventory/nb_inventory.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_device.py
- tests/integration/targets/inventory/files/test-inventory-legacy.json
- tests/integration/targets/inventory/files/test-inventory-options-flatten.yml
- tests/integration/targets/inventory/files/test-inventory-options.json
- tests/integration/targets/inventory/files/test-inventory-plurals-flatten.json
- tests/integration/targets/inventory/files/test-inventory-plurals.json
- tests/integration/targets/inventory/files/test-inventory.json
- tests/integration/targets/latest/tasks/netbox_device.yml
- tests/unit/inventory/test_data/refresh_url/data.json
Taking over #244 to get testing taken care of.
> Enhancement: Add local_context_data to inventory plugin & netbox_device

- plugins/lookup/nb_lookup.py
> Bugfix: Set validate_certs default to True

- plugins/module_utils/netbox_utils.py
- tests/integration/targets/latest/tasks/netbox_cable.yml
- tests/integration/targets/latest/tasks/netbox_device_interface.yml
- tests/integration/targets/regression/tasks/main.yml
- tests/unit/module_utils/test_data/build_query_params_no_child/data.json
Fixes #282 
The searches allowed on device_bay/interface_template to properly search those endpoints
> Bugfix: Change search type for device_bay/interface_template to devicetype_id

- plugins/inventory/nb_inventory.py
- tests/integration/targets/inventory/files/test-inventory-options-flatten.yml
> Make a copy of ipaddress before modifying to not break caching.

- plugins/inventory/nb_inventory.py
Added exception handling for HTTPError to provide response body when encountering HTTPError
Fixes #294
> Bugfix: nb_inventory - Exception handling for HTTPError

- plugins/inventory/nb_inventory.py
- tests/integration/targets/inventory/files/test-inventory.json
- tests/integration/targets/inventory/files/test-inventory.yml
Takes over #286 to add tests and get merged in
> Enhancement: group_by for servers

- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_service.py
- tests/integration/targets/latest/tasks/netbox_service.yml
> Bugfix: Add required_one_of to netbox_service to allow device or virtual_machine

- plugins/module_utils/netbox_utils.py
- tests/integration/netbox-deploy.py
> Bugfix: Fix virtual_machine_role search to search using slug

- plugins/inventory/nb_inventory.py
- plugins/module_utils/netbox_utils.py
> feat: add follow_redirects option

- plugins/inventory/nb_inventory.py
Fixes #287. Code stolen from @dotSource-GmbH.
Made a mess of some authorship revisions on the #333 fork. Starting fresh.
> Bugfix: nb_inventory.py group_by: tags (NB 2.9+)

- plugins/modules/netbox_virtual_machine.py
local_context_data can now be created/updated within Netbox
> Added local_context_data to data

- plugins/inventory/nb_inventory.py
Fixes #213 using documentation.
> Documentation: Inventory - Added example of keyed_groups

- plugins/module_utils/netbox_extras.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_tag.py
- plugins/modules/netbox_tags.py
- tests/integration/targets/latest/tasks/main.yml
- tests/integration/targets/latest/tasks/netbox_tag.yml
- tests/integration/targets/v2.8/tasks/main.yml
- tests/integration/targets/v2.8/tasks/netbox_tag.yml
- tests/sanity/ignore-2.10.txt
Fixes #365 and #288 
Thanks to @pkorovin for all the work on this!
> New Module: netbox_tag

- plugins/module_utils/netbox_utils.py
- tests/integration/netbox-deploy.py
- tests/integration/targets/latest/tasks/netbox_cable.yml
- tests/integration/targets/v2.8/tasks/netbox_cable.yml
- tests/unit/module_utils/test_data/build_query_params_child/data.json
> Bugfix: Type for termination_a_type and circuits.circuittermination

- plugins/modules/netbox_virtual_machine.py
> Added comments option for netbox_virtual_machine

- .github/workflows/main.yml
This is to help troubleshoot an issue with a user and add testing a different Python version.
> Added testing for Python 3.7

- plugins/inventory/nb_inventory.py
- tests/integration/targets/inventory-latest/files/test-inventory-options-flatten.json
- tests/integration/targets/inventory-latest/files/test-inventory-options-flatten.yml
- tests/integration/targets/inventory-latest/files/test-inventory-options.json
- tests/integration/targets/inventory-latest/files/test-inventory-options.yml
- tests/integration/targets/inventory-latest/files/test-inventory-plurals-flatten.json
- tests/integration/targets/inventory-latest/files/test-inventory-plurals-flatten.yml
- tests/integration/targets/inventory-latest/files/test-inventory-plurals.json
- tests/integration/targets/inventory-latest/files/test-inventory-plurals.yml
- tests/integration/targets/inventory-latest/files/test-inventory.json
- tests/integration/targets/inventory-latest/files/test-inventory.yml
Fixes #397 
This should allow **group_by** for status.
> Inventory: Get group_by status working properly

- plugins/module_utils/netbox_utils.py
- tests/integration/netbox-deploy.py
- tests/integration/targets/regression-latest/tasks/main.yml
- tests/integration/targets/regression-v2.9/tasks/main.yml
> Allow Integers for IDs to be passed into lists.

- plugins/modules/netbox_site.py
- tests/integration/targets/latest/tasks/netbox_site.yml
- tests/integration/targets/v2.9/tasks/netbox_site.yml
Updated latitude/longitude to be strings instead of floats for idempotency and that is what NetBox is expecting.
Fixes #416
> Bugfix: netbox_site: Changed lat/longitude from float to str and updated tests

- plugins/module_utils/netbox_ipam.py
- plugins/module_utils/netbox_utils.py
- tests/integration/targets/regression-latest/tasks/main.yml
- tests/integration/targets/regression-v2.9/tasks/main.yml
> Bugfix: netbox_utils - If query_dict is None, fail and provide meaningful error message

- plugins/module_utils/netbox_utils.py
- tests/integration/targets/latest/tasks/netbox_ip_address.yml
- tests/integration/targets/v2.9/tasks/netbox_ip_address.yml
> Bugfix: Removed logic to manipulate query params for ip_address

- plugins/modules/netbox_device_role.py
- plugins/modules/netbox_platform.py
Existing playbooks fail with missing description field.
> Add description field to argument_spec

- CHANGELOG.rst
- changelogs/changelog.yaml
- galaxy.yml
- poetry.lock
- pyproject.toml
> Release v2.1.0

- plugins/module_utils/netbox_utils.py
> Allow rack to be in the query_params_ids

- plugins/modules/netbox_cluster_type.py
- plugins/modules/netbox_ipam_role.py
- plugins/modules/netbox_manufacturer.py
- plugins/modules/netbox_rir.py
Add missing description suboptions
> Enchancement: add description suboption

- plugins/modules/netbox_device_interface.py
- plugins/modules/netbox_interface.py
Allow using the 'label' field in netbox_device_interface module
> Added 'label' field to interface

- plugins/modules/netbox_tenant.py
Simple fix for something that threw me for a second.
> Fixes example to match argspec

- plugins/modules/netbox_device_interface.py
support custom_field in Interface added in Netbox v2.11
add https://github.com/netbox-community/ansible_modules/issues/491
Fixes #491 
- add interface custom_field
> Add interface custom field for 2.11

- README.md
Reverts netbox-community/ansible_modules#527
👋
> Revert "Update readme to advise looking for new maintainer."

- plugins/modules/netbox_region.py
Correct the examples provided in the netbox_region module.
> Documentation: netbox_region - Correct examples

- plugins/inventory/nb_inventory.py
> Invalid NetBox readthedocs URL in nb_inventory docs

- README.md
Add links to Slack and tidy up formatting.
I believe this is the right Slack link, though if someone could confirm that would be great.
> README: Slack link and tidyup

- plugins/module_utils/netbox_ipam.py
This allows it to be subscriptable
Co-Authored-By: @JerradGit
Fixes #555
> Convert attached_ips generator to a list

- plugins/lookup/nb_lookup.py
Not sure if it's simple as that to add new API endpoints, but as far as I can tell it works in my environment.
> added connected-device API endpoint

- plugins/modules/netbox_inventory_item.py
- tests/integration/targets/v2.11/tasks/netbox_inventory_item.yml
- Add label as argument to module netbox_inventory_item
- Add custom fields argument to module netbox_inventory_item
- Add label to inventory_item test
> Fixes #630 Add label and custom fields to inventory item module

- plugins/module_utils/netbox_utils.py
- On 2.11, cast vcpu value to string
> Fixes #616 Ensure netbox_virtual_machine is idempotent on 2.11

- plugins/inventory/nb_inventory.py
- tests/unit/inventory/test_nb_inventory.py
Hi, I'd like to propose a change to the _nb_inventory_ that speeds up the fetching of data on subsequent runs.
Currently, the NetBox API docs are always downloaded at each inventory script run.
This takes a lot of time to finish as the file is now over 60000 lines long.
Enabling the cache option is not a good solution for this as it will also cache all the objects gathered by the script.
My solution leverages a new _status_ API endpoint added in NetBox 2.10 which returns NetBox version among other parameters.
The API version from the GET status call is then compared with the locally dumped JSON with API docs. If the versions match then locally cached JSON file is loaded. In any other scenario the API docs are fetched as usual.
When implemented my test inventory was gathered in 3s whereas …
> Cache openapi dump locally

- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_virtual_chassis.py
Fix a number of things with the virtual chassis module:
- ~~Make name a required suboption (as it is in NetBox's API docs)~~
- Add custom_fields to the module
- Fix the creation bug when no master is defined as outlined in #477
> Closes #477: Fix virtual chassis functionality

- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_device_interface.py
- plugins/modules/netbox_vm_interface.py
The option bridge/vm_bridge: is added to the netbox_device_interface and netbox_vm_interface modules.
* [X ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X] I have explained my PR according to the information in the comments or in a linked issue.
* [ X] My PR targets the `devel` branch.
> Add bridge as an option to netbox_device_interface and netbox_vm_interface

- plugins/modules/netbox_cable.py
- plugins/modules/netbox_circuit_type.py
- plugins/modules/netbox_cluster_group.py
- plugins/modules/netbox_cluster_type.py
- plugins/modules/netbox_device_role.py
- plugins/modules/netbox_ipam_role.py
- plugins/modules/netbox_location.py
- plugins/modules/netbox_manufacturer.py
- plugins/modules/netbox_platform.py
- plugins/modules/netbox_power_panel.py
- plugins/modules/netbox_rack_role.py
- plugins/modules/netbox_rir.py
- plugins/modules/netbox_site_group.py
- plugins/modules/netbox_tenant_group.py
Add custom_fields dictionary to modules without it.
> Add custom_fields to remaining modules

- plugins/modules/netbox_circuit_type.py
- plugins/modules/netbox_cluster_group.py
- plugins/modules/netbox_cluster_type.py
- plugins/modules/netbox_device_role.py
- plugins/modules/netbox_ipam_role.py
- plugins/modules/netbox_location.py
- plugins/modules/netbox_manufacturer.py
- plugins/modules/netbox_platform.py
- plugins/modules/netbox_power_panel.py
- plugins/modules/netbox_rack_role.py
- plugins/modules/netbox_rir.py
- plugins/modules/netbox_service.py
- plugins/modules/netbox_site_group.py
- plugins/modules/netbox_tenant_group.py
- plugins/modules/netbox_vlan_group.py
Add tags to modules missing it.
> Add tags to modules missing it

- plugins/module_utils/netbox_extras.py
- plugins/module_utils/netbox_utils.py
- plugins/module_utils/netbox_wireless.py
- plugins/modules/netbox_custom_field.py
- plugins/modules/netbox_custom_link.py
- plugins/modules/netbox_export_template.py
- plugins/modules/netbox_webhook.py
- tests/integration/targets/v3.1/tasks/main.yml
- tests/integration/targets/v3.1/tasks/netbox_export_template.yml
- tests/integration/targets/v3.1/tasks/netbox_webhook.yml
> Add netbox_webhook as module

- .github/workflows/release.yml
Adjustment of the release workflow.
> Fixes #761: Remove unnecessary steps in release

- plugins/modules/netbox_device_interface.py
- plugins/modules/netbox_device_interface_template.py
- poetry.lock
- pyproject.toml
#818 
Add PoE mode and PoE type to netbox_device_interface module.
> Fix #818: Add PoE abilities to netbox_device_interface

- plugins/modules/netbox_prefix.py
#813 
Add mark_utilized to netbox_prefix module.
> #813: Add mark_utilized to netbox_prefix

- plugins/modules/netbox_cable.py
#815 
Change cable length to float.
> #815: Change cable length to float

- plugins/modules/netbox_location.py
> #812: Add tenant to location

- plugins/inventory/nb_inventory.py
#835 
improved documentation example
...
...
...
...
...
* [x ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [x ] I have explained my PR according to the information in the comments or in a linked issue.
> For ansible-modules #835 : Add example of exclusion search

- docs/getting_started/how-to-use/modules.rst
To show usage of the new module_defaults.
> Add documentation for module_default

- plugins/modules/netbox_device.py
- plugins/modules/netbox_device_type.py
Add option airflow to device and device_type
> Add airflow to device and device_type

- .github/workflows/main.yml
Seems like we've been behind on updating our GitHub action for poetry.
> Update poetry action 

- plugins/modules/netbox_webhook.py
#925
Conditions setup runs as expected.
Playbook runs without error when `conditions` section is defined.
Fixes the NetBox API's _400 Bad Request_ answer when conditional webhook setup required.
Conditions must be formatted as dictionary.
Type was modified in item description.
netbox_webhook - Fix conditional webhook setup
> Conditions setup fix

- CHANGELOG.rst
Missed it in the release itself...
> Generate changelog for 3.11.0

- plugins/module_utils/netbox_ipam.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_asn.py
- tests/integration/targets/v3.2/tasks/main.yml
- tests/integration/targets/v3.2/tasks/netbox_asn.yml
- tests/integration/targets/v3.3/tasks/main.yml
- tests/integration/targets/v3.3/tasks/netbox_asn.yml
- tests/integration/targets/v3.4/tasks/main.yml
- tests/integration/targets/v3.4/tasks/netbox_asn.yml
[#743](https://github.com/netbox-community/ansible_modules/issues/743)
Added module for ASN
- The ability to add, update or delete ASN using ansible modules.
- Added tests for netbox_asn
netbox.netbox.netbox_asn - Create, update or delete ASN in NetBox
> Feature #743: Added module for ASN

- changelogs/fragments/issue-951.yml
- plugins/inventory/nb_inventory.py
Closes #951 
groups are created for each site_group when using the group_by feature with site_group
...
No groups created for site_groups
Working group_by feature
N/A
...
> Fix nb_inventory group_by by site_group

- plugins/modules/netbox_aggregate.py
> Add tenant to netbox_aggregate

- plugins/modules/netbox_circuit_type.py
- plugins/modules/netbox_device_interface.py
> Add description to netbox_circuit_type and wwn to netbox_device_interface

- tests/integration/targets/v3.6/tasks/main.yml
- tests/integration/targets/v3.6/tasks/netbox_ip_address.yml
- tests/integration/targets/v3.6/tasks/netbox_platform.yml
- tests/integration/targets/v3.6/tasks/netbox_rack.yml
Adjust tests to pass. 
- Comment out test with NetBox bug
- Remove tests with Napalm references
> Fix tests temporary

- docs/requirements.txt
- tests/integration/targets/v3.6/tasks/netbox_ip_address.yml
- After release NetBox 3.6.4, include ip address tests again.
- Try to fix the docs issue by pinning jinja2 dependency
> Fix CI test and update sphinx configuration

- changelogs/changelog.yaml
namespace was mispelled.
N/A
Just fixing a typo.
...
N/A
...
Ensure consistency.
...
N/A
...
N/A
...
> Typo fix only

- meta/runtime.yml
- plugins/module_utils/netbox_dcim.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_module.py
- plugins/modules/netbox_module_bay.py
- tests/integration/targets/v3.5/tasks/netbox_module.yml
- tests/integration/targets/v3.5/tasks/netbox_module_bay.yml
- tests/integration/targets/v3.6/tasks/netbox_module.yml
- tests/integration/targets/v3.6/tasks/netbox_module_bay.yml
- tests/integration/targets/v3.7/tasks/netbox_module.yml
- tests/integration/targets/v3.7/tasks/netbox_module_bay.yml
[Feature]: Add the module Module #769
Add support for : 
Module and Module bay weren't supported.
Add new functionality to Ansible Netbox.Netbox collection.
Please update wiki to include module & module_bay support.
Add support for Module and Module Bay.
- netbox_module
- netbox_module_bay
> #769 : Add support for Module/Module Bay

- docs/plugins/nb_inventory_inventory.rst
In the previous PR https://github.com/netbox-community/ansible_modules/pull/1081 this option had not yet been documented.
I wish to change that and add documentation for this option.
Add documentation for the option `oob_ip_as_primary_ip` in nb_inventory plugin
...
...
...
...
...
> Add documentation for the option `oob_ip_as_primary_ip` in nb_inventory plugin

- README.md
#1238
Housekeeping – README.md updates
See related issue
- The project and community will benefit by having a top-level README which is better aligned with current best practices among Ansible collections.
- No drawbacks are foreseen.
- Since no code changes are involved, there are no implications on backward compatibility.
Updated top-level `README.md` to align with current Ansible collection best practices
> Updates to top-level README.md to align collection with Ansible best practices Fixes #1238

- .github/workflows/tests.yml
- changelogs/fragments/fix_ci.yml
> fixes #1251

- .github/workflows/tests.yml
- CHANGELOG.rst
- changelogs/changelog.yaml
> Issue 1253

- .github/workflows/main.yml
Adjust CI to docker compose v2.
> Fix CI with docker compose

- changelogs/fragments/1309-feature-add-serial-number-to-vm.yml
- plugins/modules/netbox_virtual_machine.py
Fixes #1309 
Add the possibility to use the new serial number field on virtual machines
Add and update serial number on virtual machines in NetBox v4.1.x
Nice to be able to update serial number on VMs using Ansible
...
minor_changes:
- Add `serial` to `netbox_virtual_machine` module (https://github.com/netbox-community/ansible_modules/issues/1309)
> Feature add serial number to vm

- changelogs/fragments/41_updates.yml
- plugins/module_utils/netbox_dcim.py
- plugins/module_utils/netbox_utils.py
- plugins/modules/netbox_rack.py
- tests/integration/targets/v4.1/tasks/main.yml
- tests/integration/targets/v4.1/tasks/netbox_permission.yml
- tests/integration/targets/v4.1/tasks/netbox_rack.yml
- tests/integration/targets/v4.1/tasks/netbox_token.yml
- tests/integration/targets/v4.1/tasks/netbox_user.yml
- tests/integration/targets/v4.1/tasks/netbox_user_group.yml
- tests/integration/targets/v4.1/tasks/netbox_virtual_machine.yml
Adjust modules for 4.1:
- Handle form_factor in netbox_rack
- Fix device_type_id filter
- Adjusts netbox_user, netbox_token, netbox_user_group, netbox_permission tests for new password requirements
- Add serial to netbox_virtual_machine test
> Various 4.1 updates

- plugins/inventory/nb_inventory.py
as per https://github.com/netbox-community/ansible_modules/issues/1380#issuecomment-2705434572
#1380
documentation change
> Remove 404 link

- docs/plugins/nb_lookup_lookup.rst
one opened bracket but two closed
No new behavior, just Doc Syntax fix
...
Syntax Error in Example
...
...
...
Doc: Fixed syntax error in netbox.netbox.nb_lookup
...
> Fixed syntax error
