.travis.yml
CHANGELOG.md
galaxy.yml
plugins/module_utils/netbox_utils.py
tests/integration/integration-tests.yml

There are certain fields for modules that are tied to static choices and are dynamically determined via the string passed in and doing a lookup within netbox_utils.
This PR fixes #47 and allows integers to be passed in and doesn't attempt to dynamically determine what that integer value should be and just passes the integer to the API. This affects all fields that are within the [REQUIRED_ID_FIND](https://github.com/FragmentedPacket/netbox_modules/blob/devel/plugins/module_utils/netbox_utils.py#L348) within netbox_utils.
If the integer passed in is not a valid choice, the API should return an error and fail the module.

Fix passing in integer for endpoint choices

---

.travis.yml
plugins/lookup/netbox.py

Update lookup plugin to remove documentation stating that secrets cannot be decrypted. Added docs on how to decrypt secrets using the `key_file` option
Fixes #30

update lookup docs

---

plugins/module_utils/netbox_dcim.py
plugins/module_utils/netbox_utils.py
plugins/modules/netbox_device_type.py
tests/integration/integration-tests.yml

Fixes #74 
Made **slug** not required, but model is now required. Slug can still be passed in, but if not, it will slugify the model.

BugFix: Fix device type slug

---

plugins/module_utils/netbox_ipam.py
tests/integration/integration-tests.yml

Fixes #72 
This is done by attempting to convert the address to `ipaddress.ip_network` and then to_text to get a textual representation with the mask.

BugFix: netbox_ip_address: normalize address to /32 if no cidr provided

---

plugins/module_utils/netbox_utils.py
tests/unit/module_utils/test_netbox_base_class.py

This PR should fix #85 
Converts the identical keys to the proper key that Netbox is expecting when building query params

BugFix: Convert keys in build_query_params

---

README.md
plugins/module_utils/netbox_utils.py
tests/integration/integration-tests.yml
tests/unit/module_utils/fixtures/choices/circuits.json
tests/unit/module_utils/fixtures/choices/device_types.json
tests/unit/module_utils/fixtures/choices/devices.json
tests/unit/module_utils/fixtures/choices/interfaces.json
tests/unit/module_utils/fixtures/choices/prefixes.json
tests/unit/module_utils/fixtures/choices/racks.json
tests/unit/module_utils/fixtures/choices/services.json
tests/unit/module_utils/fixtures/choices/sites.json
tests/unit/module_utils/fixtures/choices/virtual_machines.json
tests/unit/module_utils/fixtures/choices/vlans.json
tests/unit/module_utils/test_netbox_base_class.py

Fixes #67 
This PR removes static choices that were defined in `plugins/module_utils/netbox_utils.py` and instead makes API calls to the appropriate endpoint to fetch the choices for the endpoint.
Updated unit testing a little bit, but they need more work. I will refactor those in a separate PR.

Feature: Removed static choices and return choices from API

---

plugins/inventory/netbox.py

Fixes #58 
This just returns the raw output from the API call and doesn't include any doctoring. Below is an example:
```
"test100": {
"device_roles": [
"Core Switch"
],
"device_types": [
"Cisco Test"
],
"manufacturers": [
"Cisco"
],
"services": [
{
"created": "2020-02-13",
"custom_fields": {},
"description": "",
"device": {
"display_name": "test100",
"id": 1,
"name": "test100",
"url": "http://netbox-demo.org:32768/api/dcim/devices/1/"
},
"id": 1,
"ipaddresses": [],
"last_updated": "2020-02-13T19:36:08.076923Z",
"name": "test",
"port": 8080,
"protocol": {
"id": 6,
"label": "TCP",
"value": "tcp"
},
"tags": [],
"virtual_machine": null
}
],
"sites": [
"Test Site"
],
}
```

Inventory-Feature: Added services lookup

---

plugins/inventory/netbox.py

Fixes #59 
This should fix the group_by issue, but may want to be revisited as they Ansible appears to be moving to group_names requiring to use underscores.
This at least fixes the issue above for the time being, but I think Ansible also does the conversions itself.

Inventory-bug: Changed the lookups to use slug where available

---

plugins/inventory/netbox.py

Fixes #60 
This just adds work from PR in Ansible core to address this. All raw data again, but gets it implemented.

Inventory-feature: Added interfaces and ip addresses

---

plugins/module_utils/netbox_utils.py
tests/unit/module_utils/test_netbox_base_class.py

Fixes #106 
This removes the static finding of the lag choice when lag is defined as a dictionary and uses the new endpoints that collects the choices from the API, this should be backwards compatible as well.

BugFix: netbox_device_interface: Lag defined as dict broke Netbox v2.7

---

plugins/modules/netbox_device.py
tests/integration/integration-tests.yml

Fixes #108 
If name is empty string, set UUID
I'm not 100% sure if I like this way, but I think that at least gets us over this issue for now. Hopefully we receive more input from others since this is not something i've done and don't have any strong opinion or use case for it.

BugFix: Device name - empty string tests as well

---

plugins/module_utils/netbox_tenancy.py
plugins/module_utils/netbox_utils.py
plugins/modules/netbox_site.py
plugins/modules/netbox_tenant.py
plugins/modules/netbox_tenant_group.py
tests/integration/integration-tests.yml
tests/unit/module_utils/test_data/build_query_params_no_child/data.json
tests/unit/module_utils/test_data/normalize_data/data.json

This change makes possible for deployers to define slug while site,
tenant or tenant_group creation.
Signed-off-by: Dmitriy Rabotyagov <drabotyagov@vexxhost.com>

Add slug key for sites, tenants and tenant_groups

---

.travis.yml

From the failed release job, it appears I don't need to install ansible or build the collection again and just publish on tag.

Deploy: Attempting to fix Travis Deploy to Ansible Galaxy on Tag

---

.travis.yml
galaxy.yml
plugins/inventory/nb_inventory.py
tests/integration/ansible.cfg
tests/integration/netbox-deploy.py
tests/integration/test-inventory.yml

I broke the inventory plugin by not changing the name of it in the actual file when moving namespaces for Ansible Galaxy
Correct and bumped version, added a quick inventory test to tests

BugFix: Corrected name of inventory plugin

---

plugins/module_utils/netbox_utils.py

Fixes a reported issue in #45 
When using Jinja templating, Ansible converts to string. Added an attempt to convert the value passed in to an integer

BugFix: Jinja template always passes in string, allowed find_ids method to account for that

---

plugins/modules/netbox_interface.py

Adding the legacy `netbox_interface` for proper migration to Ansible Collections and for Ansible 2.10
Fixes #124

Add legacy netbox_interface but mark it as deprecated

---

plugins/lookup/nb_lookup.py
tests/integration/integration-tests.yml

This PR adds the ability to return the raw data of the Netbox API. 
Currently when given the command `device: "{{ lookup('netbox.netbox.nb_lookup', 'devices', api_endpoint=api_url, token=api_token }}"` data is returned in the following format:
```
"device": {
"key": 7,
"value": {
"asset_tag": null,
"cluster": null,
"comments": "",
<snipped for brevity>
}
```
This adds an extra layer of complexity for usage as it increases the depth of the data structure behind a somewhat meaningless key/value construct where the Netbox object id becomes the key and the payload is hidden under value
This PR adds the option for the lookup plugin to return the raw Netbox API response in the following format
`device: "{{ lookup('netbox.netbox.nb_lookup', 'devices', api_endpoint=api_url, token=api_token, …

Added flag for raw api output

---

.travis.yml
README.md
galaxy.yml
plugins/inventory/nb_inventory.py
plugins/module_utils/netbox_utils.py
plugins/modules/netbox_interface.py

Still a work in progress. Running into issues with Ansible 2.10 dev - ipaddress compat class for Python 2.7 hosts has been moved to the netcommon collection. Need to work out how this import should work now.

Update Travis test environments to Netbox 2.6, 2.7

---

plugins/inventory/nb_inventory.py

Querying every single device's services as a separate HTTP request can be very slow. Allow users to disable this (similar to interfaces) if it is not required.
This makes the inventory usable again, until #143 can be implemented fully

Inventory: make it optional to query for services (#143)

---

plugins/inventory/nb_inventory.py

Fixes #138 
Added `group_names_raw` to provide the group name slug rather than prepending with the group_by option.
e.g. Before
```
group_by:
- device_roles
device_roles_core-switch
```
e.g. After
```
group_by:
- device_roles
core-switch
```
This also replaces any dash in the slug to an underscore since Ansible will be enforcing that moving from 2.10+. I'm open to keeping it as just returning the slug so please discuss what you guys think is the best approach.

Enhancement: Added option to not prepend group names with group_by option

---

plugins/modules/netbox_device_interface.py
plugins/modules/netbox_vm_interface.py

Fixes #158 
This just removes the choices for mode from `netbox_device_interface` and `netbox_vm_interface` and the NetBox API will throw the error back as you can use the slug or regular value.
@ThomasADavis Do you mind testing this to make sure you're seeing the behavior you're expecting?

Enhancement: Removed choices for mode and will allow API to return error

---

ansible.cfg
plugins/module_utils/netbox_utils.py
tests/integration/v2.6/tasks/netbox_device_interface.yml
tests/integration/v2.7/tasks/netbox_device_interface.yml
tests/integration/v2.8/tasks/netbox_device_interface.yml

Fixes #166 
If lag is defined as just a string, it will send it to `_build_query_params` to properly build the query to find the LAG interface.

BugFix: Find proper LAG if not defined as dictionary

---

README.md

Fixes #169 
I think using the inventory from CLI is documented within the plugin (still awaiting Ansible doc hosting), but wanted to add quick steps to getting it working within AWX/Tower

Documentation: Using inventory plugin in AWX/Tower

---

plugins/inventory/nb_inventory.py

Fixes #177 
`LOGIN_REQUIRED` is FALSE by default, but does require one more modification to `EXEMPT_VIEW_PERMISSIONS` to allow anyone to read from NetBox without authorization.
This just modifies the headers for the calls and adds the token into the headers if it is set.

Inventory: Remove token being required for nb_inventory

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_device_interface.py

Fixes #193 
This adds the following:
- Deprecation warning for `form_factor` option.
- Add `type` to options.
- Adds clearer messaging when using `form_factor` on 2.7 and to change to using `type`
I decided not to add any logic to change the form_factor key when updating the object and just clarify the warning as I will remove any form_factor code on 0.3.0 release which will probably be sooner than later.

Bugfix: netbox_device_interface: Add type and add deprecation to form_factor option

---

plugins/module_utils/netbox_utils.py

Fixes #211 
This will allow user to pass boolean or string pointing to a private key.

Allow private key for validate_certs

---

plugins/lookup/nb_lookup.py

Fixes #216 
@dakennedy
Do you mind testing with it set and without the new option set?
I just want to see if it sets the validate_certs to True by default so it should fail for you if it's not specified and if `false`, then work for you.

Added validate_certs option for lookup plugin

---

README.md
plugins/module_utils/netbox_utils.py

Error was occurring for a user using a read-only token when attempting to use the modules. Created better error handling and messaging when encountering the error to point to the issue.

Enhancement: Added error handling for .choices() errors

---

plugins/module_utils/netbox_utils.py
tests/integration/targets/latest/tasks/netbox_ip_address.yml
tests/unit/module_utils/test_data/normalize_data/data.json
tests/unit/module_utils/test_data/normalize_integer/data.json
tests/unit/module_utils/test_netbox_base_class.py

Fixes #231 
This is more of a global fix as it converts any values passed in to integers if they're able to. This allows users to pass in IDs of objects in NetBox if queried or known.
Previously this was only in `_find_ids` method, but now moved into `_normalize_data` method.

Bugfix: Properly convert values to integers when passed into modules

---

README.md

Addresses #283 
* Adds a simple example to the README to show how to set up the inventory file so it can be used with Ansible
* Directs users to further documentations/examples

Add example of using as inventory in README

---

README.md

Update query example with correct path to plugin

---

plugins/module_utils/netbox_utils.py
tests/unit/module_utils/test_data/build_query_params_no_child/data.json

I fixed this for just two templates instead of all of them. This new code should resolve that issue.

Bugfix: Change query_dict for _templates modules to choose devicetype_id

---

changelogs/fragments/fix_tags.yml
plugins/module_utils/netbox_utils.py
tests/integration/targets/regression/tasks/main.yml

Bug was introduced in #247. I forgot to update the object to check for any other possible updates if tags were specified.
Fixes #324 
Fixes #311 
Fixes #316 
Fixes #322

Bugfix: Fixes no endpoint updates if tags are specified

---

docs/getting_started/index.rst

Small adjustment on the custom venv with Ansible Tower. Our production Tower installation ships with Python 2 by default. We need to add multiple custom venv for different uses.

Small adjustment on the custom venv

---

plugins/inventory/nb_inventory.py

IP addresses missing from virtual machine interfaces

---

plugins/inventory/nb_inventory.py

Fixes #312 
This will print a red error message for any endpoints that return a 403. This should help users to determine why the inventory may not look as expected when they're using RBAC.

Bugfix: Inventory - Prevent failing inventory on 403

---

docs/plugins/modules/netbox_device_interface/netbox.netbox.netbox_device_interface_module.rst
plugins/modules/netbox_device_interface.py

Some of the descriptions were copied from the `netbox_prefix` module into the `netbox_device_interface` module. This PR is just to correct those.

Correct labels from 'prefix' to 'interface'

---

plugins/lookup/nb_lookup.py
tests/integration/targets/latest/tasks/netbox_lookup.yml
tests/integration/targets/v2.8/tasks/netbox_lookup.yml

Enhancement: Allow id for api_filter that uses .get instead of .filter

---

plugins/inventory/nb_inventory.py

This patch allows overriding ansible_host variable via a config_context or custom_field
Sometimes the primary ip of a device/vm does not match the one that ansible should use to manage it (eg nat, management network ecc)

Move extracted_primary_ip* on top of _fill_host_variables

---

plugins/modules/netbox_ip_address.py

Fixes #373
Not a great way, but appears you just document in the `DOCUMENTATION` description for the option.

Updated documentation for the family in netbox_ip_address

---

plugins/module_utils/netbox_utils.py
tests/integration/targets/latest/tasks/netbox_ip_address.yml
tests/integration/targets/regression-latest/tasks/main.yml
tests/integration/targets/v2.8/tasks/netbox_ip_address.yml

Fixes #372 
There is logic that adds and manipulates data in the query params that should be skipped when a user defines `user_query_params`.

Fixed user_query_params to pass before module_data is considered

---

plugins/inventory/nb_inventory.py
tests/integration/netbox-deploy.py
tests/integration/targets/inventory-latest/files/test-inventory-legacy.json
tests/integration/targets/inventory-latest/files/test-inventory-options-flatten.json
tests/integration/targets/inventory-latest/files/test-inventory-options.json
tests/integration/targets/inventory-latest/files/test-inventory-options.yml
tests/integration/targets/inventory-latest/files/test-inventory-plurals-flatten.json
tests/integration/targets/inventory-latest/files/test-inventory-plurals.json
tests/integration/targets/inventory-latest/files/test-inventory.json
tests/integration/targets/inventory-v2.8/files/test-inventory-legacy.json
tests/integration/targets/inventory-v2.8/files/test-inventory-options-flatten.json
tests/integration/targets/inventory-v2.8/files/test-inventory-options.json
tests/integration/targets/inventory-v2.8/files/test-inventory-options.yml
tests/integration/targets/inventory-v2.8/files/test-inventory-plurals-flatten.json
tests/integration/targets/inventory-v2.8/files/test-inventory-plurals.json
tests/integration/targets/inventory-v2.8/files/test-inventory.json
tests/unit/inventory/test_data/group_extractors/data.json
tests/unit/inventory/test_nb_inventory.py

Fixes #378. Adds the dns_name from the host's Primary IP to host_vars.
- Adds the dns_name option which forces IP addresses to be fetched and sets the dns_name host_var
- The interfaces option also causes IP addresses to be fetched, so the dns_name host_var will also be set with the interfaces option
- Added v2.10 fixes for the netbox_deploy.py script, but didn't fix all testing to work with v2.10. The inventory testing won't pass with v2.10
- I tested v2.9 locally and it passed. The automated testing will fail since it automatically gets latest from docker which is now v2.10.

Add dns_name option for the Primary IP's dns_name host_var

---

docs/getting_started/how-to-use/modules.rst

The `serial_number` is invalid parameter.

Fix typo on the how-to (serial number update)

---

galaxy.yml
plugins/inventory/nb_inventory.py
plugins/module_utils/netbox_ipam.py
plugins/module_utils/netbox_utils.py

The ansible.netcommon collection pushed a breaking change with the module_utils: https://github.com/ansible-collections/ansible.netcommon/commit/8cda0e6906a86790ab423b11adafa425e870926a
- Replaced the ipaddress usage with the built-in python3 ipaddress module where it was needed.
- Removed the dependency in galaxy.yml.
Fixes #452

Remove ansible.netcommon dependency

---

plugins/modules/netbox_cable.py
tests/integration/targets/latest/tasks/netbox_cable.yml
tests/integration/targets/v2.9/tasks/netbox_cable.yml

Adds tags to `DOCUMENTATION` and `argument_spec` in the netbox_cable module. An example of using tags is provided in `EXAMPLES` also.
Updates netbox_cable integration tests to include adding a tag.
Fixes #448

Enhancement: add tags to netbox_cable

---

plugins/inventory/nb_inventory.py

This fixes issue #472 
netbox-2.9 and up changed the tag format.  this converts the returned tags from an array of
instances, to a just an array of the tag slug values.
ie,
this:
```
"tags": [
{
"color": "9e9e9e",
"id": 130,
"name": "default",
"slug": "default",
"url": "http://netbox/api/extras/tags/130/"
}
],
```
becomes:
```
tags: [ 'default' ]
```

Properly handle interface tags.

---

plugins/modules/netbox_device_interface.py
tests/integration/targets/latest/tasks/netbox_device_interface.yml

Add mark_connected option to netbox_device_interface module.
Add integration test to test adding an interface that is marked as connected.
Closes #504

Enhancement: netbox_device_interface - Add mark_connected

---

plugins/inventory/nb_inventory.py
poetry.lock
pyproject.toml
tests/unit/inventory/test_nb_inventory.py

In NetBox v2.11 the RackGroup model has been renamed to Location. Its REST API endpoint has changed from `/api/dcim/rack-groups/` to `/api/dcim/locations/`
More info on NetBox release notes: https://netbox.readthedocs.io/en/stable/release-notes/#v2110-2021-04-16
This is quickfix for #492 . Tested with NetBox ee0a2f44f1bd (v2.11.2)

Inventory: Quickfix the RackGroup API URL change

---

plugins/inventory/nb_inventory.py
tests/integration/netbox-deploy.py
tests/integration/targets/inventory-latest/files/test-inventory-legacy.json
tests/integration/targets/inventory-latest/files/test-inventory-options-flatten.json
tests/integration/targets/inventory-latest/files/test-inventory-options-flatten.yml
tests/integration/targets/inventory-latest/files/test-inventory-options.json
tests/integration/targets/inventory-latest/files/test-inventory-options.yml
tests/integration/targets/inventory-latest/files/test-inventory-plurals-flatten.json
tests/integration/targets/inventory-latest/files/test-inventory-plurals-flatten.yml
tests/integration/targets/inventory-latest/files/test-inventory-plurals.json
tests/integration/targets/inventory-latest/files/test-inventory-plurals.yml
tests/integration/targets/inventory-latest/files/test-inventory.json
tests/integration/targets/inventory-latest/files/test-inventory.yml

Use locations instead of rack groups in 2.11. This still allows 2.10 or lower to function with rack groups.
Fixes #492 
- Will use locations or rack groups depending on the API version
- Adds locations to their specific site group as children
- Creates parent relationship with nested locations just like regions
- Devices are added to locations if assigned to a location. They are assigned to sites if **not** assigned to a location.
- Will throw an error if `location` is added to `group_by` and API version is 2.10 or lower
- Will throw an error if `rack_group` is added to `group_by` and API version is 2.11 or higher
I have not added any testing yet, but wanted to at least get this out there.

Full locations functionality in inventory plugin for 2.11

---

plugins/lookup/nb_lookup.py

This PR adds a `private_key` option to `nb_lookup`.
It allows the private key (for secret decryption) to be read from a variable instead of a file.
This may be useful if the private key is stored in an ansible-vault for example.
I've also clarified the documentation for `api_filter` and `raw_data`.

Add `private_key` option to `nb_lookup`.

---

plugins/inventory/nb_inventory.py
plugins/module_utils/netbox_utils.py

Added custom certificate support for TLS authentication.
With `ansible-inventory` it can be used like this:
```
---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://path.to.your.netbox:443
token: 0123456789abcdef0123456789abcdef01234567
validate_certs: true
cert: "/path/to/client.cert"
key: "/path/to/client.key"
ca_path: "/path/to/ca.crt"
config_context: false
interfaces: true
```
With `ansible-playbook` it can be used like this:
```
- hosts: all
gather_facts: no
connection: local
environment:
REQUESTS_CA_BUNDLE: "/etc/ssl/certs/ca-certificates.crt"
vars:
netbox_url: "https://path.to.your.netbox:443"
netbox_token: "0123456789abcdef0123456789abcdef01234567"
cert:
- "/path/to/client.cert"
- "/path/to/client.key"
tasks:
- name: "Task name"
delegate_to: localhost
block:
- name: "BLOCK …
```

Added custom certificate support

---

plugins/inventory/nb_inventory.py

The documentation for a plugin's `options` are located [here]( https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec).
Changing this to `elements` allows users to select "Any of" the options in the list rather than "The whole list (or not)" As it stands the `default: []` prevents the plugin from loading at all.

Fix plugins/inventory -> options/group_by

---

plugins/inventory/nb_inventory.py

Reverts netbox-community/ansible_modules#537
See the original PR for my comments.  This should be ripped out for now.

Revert "Fix plugins/inventory -> options/group_by"

---

plugins/modules/netbox_virtual_machine.py
tests/integration/targets/v2.11/tasks/netbox_virtual_machine.yml
tests/integration/targets/v3.0/tasks/netbox_virtual_machine.yml

- Change option `vcpu` on module `netbox_virtual_machine` from `int` to `float`
- Adjust `netbox_virtual_machine` test on 2.11 to use fractional vCPU
This change is backwards compatible and corrects behaviour after NetBox 2.11's change of the vCPU attribute to float.

Fix #562 Change vCPU on Virtual Machine to float

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_device_interface.py
plugins/modules/netbox_vm_interface.py
tests/integration/targets/v2.11/tasks/netbox_device_interface.yml
tests/integration/targets/v2.11/tasks/netbox_vm_interface.yml

This fixes #549 and #507 
This allows the parent of a interface to be assigned.
Both virtual (vm) and real (device)
for real devices, the label is 'parent_interface'.
for vm devices, the label is 'parent_vm_interface'.
This is done this way for several reasons.
1) prevention of a collision with the 'parent' label in other modules.
2) assignment of the correct netbox API.
The parent can only be on the same device/VM. Trying to assign a different interface from a different device will fail.  The child interface also must be a virtual interface on real devices, they already are virtual on VM's.
This has been tested in my environment for several months now.

This allows the addition of the parent to an interface.

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_site.py

- Change latitude and longitude parameters from str to float to reflect the change in NetBox 3.0
- On versions lesser than NetBox 3.0, cast latitude and longitude to str

Fixes #618 Ensure NetBox site module is idempotent between NetBox versions

---

.github/workflows/main.yml
changelogs/fragments/619-v3.0-ci-fixes.yml
tests/integration/targets/inventory-v3.0/files/test-inventory-legacy.json
tests/integration/targets/inventory-v3.0/files/test-inventory-options-flatten.json
tests/integration/targets/inventory-v3.0/files/test-inventory-options.json
tests/integration/targets/inventory-v3.0/files/test-inventory-options.yml
tests/integration/targets/inventory-v3.0/files/test-inventory-plurals.json
tests/integration/targets/inventory-v3.0/files/test-inventory.json
tests/integration/targets/v3.0/tasks/netbox_lookup.yml
tests/integration/targets/v3.0/tasks/netbox_site.yml
tests/integration/targets/v3.0/tasks/netbox_virtual_machine.yml

Fixes #590 
This PR updates the integration tests to work with v3.0
I had to disable the `netbox_site` idempotency test because of #618. Therefore, I'm creating this PR as a draft.
Also, we should consider running integration tests with Python 3.8 or higher as Ansible 2.12 will require it.

Fix integration tests with v3.0

---

plugins/modules/netbox_vm_interface.py

Currently it's not possible to set custom fields with module `netbox_vm_interface`.  
The goal of this PR is to resolve this issue.

Add custom fields to vm interface

---

plugins/module_utils/netbox_dcim.py

This attempts to fix the performance when using NetBox versions < 3.0.6 and is a continuation of the work done in #608

Enable faster lookups on Netbox version < 3.0.6

---

plugins/module_utils/netbox_utils.py
tests/integration/targets/v2.10/tasks/netbox_vrf.yml
tests/integration/targets/v2.11/tasks/netbox_vrf.yml

When data dict contains a key with values in a list the `NetboxModule._find_ids()` method would erroneously look for the whole list as pynetbox query parameter. Obviously netbox would return multiple items and pynetbox would fail on `get()` and the module would return `More than one result returned for [field name]`
This fixes this behavior.
Closes #569

Use the individual list items rather than the whole list when looking for objects in netbox

---

plugins/inventory/nb_inventory.py

This PR satisfies **(Issue #640)** without causing any changes to default functionality.
Both the extension of Site Data and Prefix Data are enabled by additional parameters passed to the module.
`site_data: (boolean)`
`prefixes: (boolean)`
These changes follow the same methodology as the interfaces option.
No changes in the default behavior of the module in order to guarantee legacy applications will continue working as intended.
The site_data parameter will cause the entire data structure returned by the /api/dcim/sites API call to be captured and inserted into hostvars appropriately for each device in inventory, instead of just the slug that is collected currently.
The prefixes option extends this section of the hostvars further by nesting the datastructure of the prefix assigned to …

Inventory module site and prefix data extended

---

plugins/lookup/nb_lookup.py

This fixes #670 
Adds a check for pynetbox v6.4.0.  If the current pynetbox is too old, simply says so when run with a '-v'.

adding pynetbox check and wireless endpoints for netbox v3.1

---

plugins/inventory/nb_inventory.py

Fixes: #694 
In older NetBox versions the prefix_count attributes on /api/dcim/sites/<site> is null, not 0 as with later versions. Make sure the check is expanded to check that the prefix_count is not None.

Add check for prefix_count for older NetBox versions

---

plugins/modules/netbox_inventory_item.py

Fixes: #695 
Add an example of using parent_inventory_item in netbox_inventory_item.
If your parent inventory item is unique you can just use the name in parent_inventory_item:. If your inventory item is not unique (as I suspect is the case in most environments) you can use 
```
parent_inventory_item:
name: inventory item name
device: device name
```

695 inventory item documentation

---

plugins/module_utils/netbox_utils.py

Fixes: #703 
NetBox versions without the API endpoint /api/status currently fails because we extract the full_version variable from it. This fix will try to get the full_version from the endpoint, and upon failure construct the full_version using the short version (2.9) and add a .0 (so 2.9 will be 2.9.0). The full_version variable is used in some checks where functionality changed mid-NetBox version.

#703 Handle "Failed to establish connection to NetBox" on older NetBox versions

---

plugins/inventory/nb_inventory.py
tests/integration/targets/inventory-v2.11/files/test-inventory-noracks.json
tests/integration/targets/inventory-v2.11/files/test-inventory-noracks.yml
tests/integration/targets/inventory-v3.0/files/test-inventory-noracks.json
tests/integration/targets/inventory-v3.0/files/test-inventory-noracks.yml
tests/integration/targets/inventory-v3.1/files/test-inventory-noracks.json
tests/integration/targets/inventory-v3.1/files/test-inventory-noracks.yml
tests/unit/inventory/test_data/group_extractors/data.json
tests/unit/inventory/test_nb_inventory.py

Hello 👋🏻 
This PR adds an option to bypass querying racks and related objects in the inventory plugin.
The motivation behind it is that in our NetBox, we have a very large amount of racks registered and, with pagination, it takes a good 40~45 seconds to gather that information, for a very limited benefit as we don't use it at all. Of course it can be mitigated by using caching but even then, it still happens occasionally when the cache expires / needs to be refreshed.
The option, by default, is set to not change anything in the current behaviour.
For the record, I've had some difficulty updating the tests. Most notably, I never managed to make the `hacking/update_test_inventories.sh` script work, so I've had to do some manual work to get to the current point and I could very well have …

inventory: Add an option bypass querying racks

---

plugins/module_utils/netbox_utils.py

Allow the filtering of `ipaddresses` in `netbox_service` to use `virtual_machine` as query params. Example:
```
netbox.netbox.netbox_service:
data:
virtual_machine: VM One
port: 443
protocol: tcp
name: https
ipaddresses:
- address: 127.0.0.1/8
virtual_machine: VM One
```
Current functionality does not allow `virtual_machine` as a query param.

Ensure netbox_service selects the right IP address

---

plugins/module_utils/netbox_utils.py
tests/unit/module_utils/test_data/build_query_params_child/data.json

Tweak the filtering parameters when filtering on VLAN groups. 
Previously you could define a VLAN an associate it to a VLAN group by doing this:
```
netbox_vlan:
data:
vid: 10
name: VLAN 10
vlan_group: My VLAN Group
```
It would do a call to `/api/vlan-groups/?slug=my-vlan-group`. This did not work when you have multiple VLANs with the same slug. So you'd try:
```
netbox_vlan:
data:
vid: 10
name: VLAN 10
vlan_group: 
slug: My VLAN Group
site: Site No 3
```
And this would do a call to `/api/vlan-groups/?slug=my-vlan-group&site_id=11`. But the VLAN group filtering is using `?site=11` to filter, so this would again return multiple results. To remediate this we now check if we're filtering a VLAN group, and if we are, we omit the `_id` on the query parameter. 
In addition, I have added `name` …

Fix #574 VLAN group returning multiple results

---

plugins/inventory/nb_inventory.py

...
...
...
None
Inventory module now properly includes the full list of prefixes assigned to a site.
* [ X ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X ] I have explained my PR according to the information in the comments or in a linked issue.
* [ X ] My PR targets the `devel` branch.

Multiple prefix per site - BUG #732

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_front_port.py
plugins/modules/netbox_front_port_template.py
plugins/modules/netbox_rear_port.py
plugins/modules/netbox_rear_port_template.py

Add `label` as parameter for netbox_front_port, netbox_rear_port. Add `label` and `description` for netbox_front_port_template and netbox_rear_port_template.
More parameters to align with NetBox functionality.

Fix #765: Add label to front and rear port modules

---

CHANGELOG.rst
changelogs/changelog.yaml
plugins/inventory/nb_inventory.py

Add some NetBox checks making sure we don't try pulling site groups on a NetBox version which does not support it.
Bug fix.

Fix #774: Add checks for NetBox version before pulling site groups

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_config_context.py

https://github.com/netbox-community/ansible_modules/issues/789 - [Feature]: Add site_groups to config_context module
This PR includes the `site_groups` model as an assignment option in the NetBox Config Context module.
It is currently not possible to assign a Config Context to a Site Group via the module.
In our case, we map Config Contexts to Site Groups and so this functionality is required to enable us to use the module.
Done.
- Add site_groups to config_context module
* [ X ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X ] I have explained my PR according to the information in the comments or in a linked issue.
* [ X ] My PR targets the `devel` branch.

Add site_group to Config Context module

---

docs/getting_started/how-to-use/advanced.rst
meta/runtime.yml

#799
This enables support for the module defaults groups feature introduced in ansible-core 2.12. Using module defaults groups one can provide default values (e.g. token, url, etc.) for a group of modules instead of having to specify them for every used module. For more details see: https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html#module-defaults-groups
This commit adds all modules available in this collection to an action group called 'netbox'. This change is backwards compatible. Older versions of Ansible just ignore this.
Currently, user has to specify module defaults (e.g. url, token) for every module in use.
This change potentially reduces the amount of boilerplate code using this collection as required parameters like e.g. ``url`` or ``token`` need …

Add action_group to enable module defaults groups

---

plugins/module_utils/netbox_utils.py
tests/unit/module_utils/test_data/build_query_params_no_child/data.json

#821 
```
netbox_cluster:
data:
name: cluster name
cluster_type: Cluster type
site:
name: CDC
```
Previously is was not possible to filter on anything other than the slug when referencing a site. This should translate to other modules as well.
None

Fix #821: Allow more than slug in a site query

---

plugins/inventory/nb_inventory.py

You can use jinja templating for the API access token in the nb_inventory 
config.
The only possibility not to have the token in clear text in the config was to
use ansible vault.
This makes it possible to use a lookup() to retrieve the token, i.e. from a 
password-manager.
Idea is stolen from the hcloud inventory.
token:  NetBox API token to be able to read against NetBox. This may be templated with jinja i.e. to use lookup().
inventory token: can now use jinja templating i.e. to use lookup()

Allow netbox api access token to be templated

---

README.md
plugins/inventory/nb_inventory.py
requirements.txt

Implements: "[Feature]: nb_inventory add group_by time_zone and time_zone_utc #788"
In the inventory source module, you can now group_by time_zone and time_zone_utc
We needed a way to group our devices by time zone or by UTC time to easily schedule playbooks during the night.
...
Currently we had to run the playbook on all hosts and then filter out the devices in the wrong time zone. This was proned to errors and accidental tasks being run that were not supposed to.
...
Im sure that other people that uses AWX/Tower to push nightly tasks to devices will like this change as it simplifies the way you can filter devices in a particular time zone.
I dont see many drawbacks as if you dont use the time_zone or time_zone_utc group by it does not affect the existing setup. It will also detect if …

Implements group_by "time_zone" and "time_zone_utc" in nb_inventory

---

meta/runtime.yml
plugins/module_utils/netbox_ipam.py
plugins/module_utils/netbox_utils.py
plugins/modules/netbox_l2vpn.py
tests/integration/inventory
tests/integration/targets/v3.3/tasks/main.yml
tests/integration/targets/v3.3/tasks/netbox_l2vpn.yml

Add module netbox_l2vpn

---

plugins/modules/netbox_virtual_machine.py

Add device field to netbox_virtual_machine to stay up to date with NetBox 3.3

Fix #848: Add device to netbox_virtual_machine

---

docs/conf.py
docs/requirements.txt

Thanks to @FragmentedPacket for the pointing me to a fix when all I needed was access to the RTD site to troubleshoot.  He goes above and beyond as always.
Closes #850
Fixes Read the Docs generation
RTD has been broken for new releases for a few releases now.

Correct readthedocs release process

---

plugins/inventory/nb_inventory.py

#860 
Test for ansible versions earlier than 2.11 in inventory plugin.

Fix #860: Make sure inventory works with ansible < 2.11

---

plugins/module_utils/netbox_utils.py
tests/integration/targets/v3.1/tasks/netbox_virtual_machine.yml
tests/integration/targets/v3.2/tasks/netbox_virtual_machine.yml
tests/integration/targets/v3.3/tasks/netbox_virtual_machine.yml

#823
Using `netbox.netbox.netbox_virtual_machine` to update the vCPU count of a VM in netbox is now idempotent from version 2.10 onward.
Using `netbox.netbox.netbox_virtual_machine` to update a VM in netbox that has custom_fields with no values is also idempotent from version 2.10 onward.
Plus a couple of pretty minor changes (that can be removed easily if undesired):
* Method `_version_check_greater` now returns a type consistent value (i.e. False instead of None by default).
* Fix for a typo in an error message.
In the current behaviour, I'd get a float value replacing my integer value on the `vcpus` field every time (netbox 2.10).
And if I had a `custom_fields` with value `None`, the module would systematically return a `state: changed` with an empty diff (netbox 2.10 and 3.2).
To do …

Fix two idempotency issues when updating VMs.

---

plugins/modules/netbox_device_bay.py

Fixes issue #864 by adding label support.
Fixes typo in installed_device description.
Adds label support to the device_bay module.
No label support for a device bay.

Fix #864 - add device bay label support to device_bay module.

---

plugins/lookup/nb_lookup.py

This adds the following new netbox-v3.3 endpoints to nb_lookup.
- cable-terminations
- inventory-item-roles
- inventory-item-templates
- l2vpn-terminations
- l2vpns
- module-bays
- module-bay-templates
- module-bay-types
- modules
- service-templates
This also corrects a mis-typed 'wireless-lan' to 'wireless-lans'

add netbox-v3.3 api endpoints to nb_lookup

---

plugins/inventory/nb_inventory.py

Netbox returns the group association via a `group` key rather than a `site_group` key. This code erroneously looks for `site_group` which will always fail.
#871 
`site_group` parent group is created containing associated `sites` as `children` host groups.
...
The old behavior results in no such group created and an empty host list is eventually created.
...
<!--
Please make your case here:
- Why do you think this project and the community will benefit from your
proposed change? Bug Fix
- What are the drawbacks of this change? None
- Is it backwards-compatible? Unsure, those unaware might end up with a larger host list than currently expected if they used `group_by: site_group` in their inventory file.
- Anything else that you think is relevant to the discussion of this PR.
I tested only …

Fixes site group lookup by using the correct key

---

plugins/modules/netbox_console_port.py
plugins/modules/netbox_console_server_port.py

This adds to the netbox_console_port.py and netbox_console_port_server.py the following:
- attach cable to pre-existing cable.
- set custom_fields
- set port label
- set port speed
- mark the cable as connected.

This updates the console port and console server port modules for the v3.3 api.

---

.github/workflows/main.yml
plugins/inventory/nb_inventory.py
plugins/lookup/nb_lookup.py
plugins/module_utils/netbox_dcim.py
poetry.lock
pyproject.toml

Make sure the modules pass sanity tests for ansible 2.13.
Ansible 2.12 is expected to go EOL in May this year.

Update CI to Ansible 2.13

---

plugins/module_utils/netbox_dcim.py
plugins/module_utils/netbox_utils.py

[#927](https://github.com/netbox-community/ansible_modules/issues/927)
Fields termination_a_id, termination_a_type, termination_b_id and termination_b_type will be converted into a_terminations and b_terminations lists for Netbox v3.3+
The cable module will work in the Netbox v3.3+ in the same way it used to in previous versions
* The cable module will be backward compatible including idempotency.
* Many to many cable connections is not implemented and requires future development.
Documentation changes are not required.
Fixed cable module compatibility with Netbox v3.3+

Fix issue #927 - cable module compatibility with NetBox v3.3

---

plugins/module_utils/netbox_utils.py
tests/unit/module_utils/test_netbox_base_class.py

It is important that the object's custom fields dictionary contains only those keys that were given by the user. Otherwise the following dictionary comparison does not work and leads to the result, that there is a difference in state even when the entries already have the desired state. The issue is caused, because the comparison takes also those entries into account that were not given by the user.
Signed-off-by: Christoph Fiehe <c.fiehe@eurodata.de>
#943: Partial update of custom fields is not idempotent
Partial updates of custom fields are now idempotent.
This fix corrects the misleading diff report and ensures idempotency when only some custom fields are updated.
This fix is fully backward-compatible and ensures idempotency in case of custom field updates.

Fixes #943: Partial update of custom fields is not idempotent

---

plugins/module_utils/netbox_ipam.py
plugins/module_utils/netbox_utils.py
plugins/modules/netbox_fhrp_group.py
tests/integration/targets/v3.2/tasks/main.yml
tests/integration/targets/v3.2/tasks/netbox_fhrp_group.yml
tests/integration/targets/v3.3/tasks/main.yml
tests/integration/targets/v3.3/tasks/netbox_fhrp_group.yml
tests/integration/targets/v3.4/tasks/main.yml
tests/integration/targets/v3.4/tasks/netbox_fhrp_group.yml

Added module for FHRP groups
- The ability to add, update or delete FHRP groups using ansible modules.
- Added tests for netbox_fhrp_group
netbox.netbox.netbox_fhrp_group - Create, update or delete FHRP groups in NetBox

Feature: Added module for FHRP groups

---

plugins/module_utils/netbox_utils.py
tests/integration/targets/regression-v3.4/tasks/main.yml

Add site as a possible filter when creating a location. You can now create a location named the same in two different sites.

Fix 958: Location filter

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_aggregate.py

Enable the use of `name` in location filter. Example:
```
netbox_rack:
data:
name: Rack One
site: site1
location:
name: Office Building
site: site1
```

Add name as filter to location

---

poetry.lock

codecov version has been changed to 2.1.13
codecov v2.1.13 will be used for testing because v2.1.12 is no longer available
This uploader is being deprecated by the Codecov team. We should consider migrating to the [new uploader](https://docs.codecov.com/docs/codecov-uploader) as soon as possible.
[The new uploader](https://github.com/codecov/uploader)
[Migration guide](https://docs.codecov.com/docs/deprecated-uploader-migration-guide#python-uploader)
[Deprecation plan](https://about.codecov.io/blog/codecov-uploader-deprecation-plan/)

Changed codecov version from 2.1.12 to 2.1.13

---

tests/integration/targets/inventory-v3.4/files/test-inventory-jinja2-filter.json
tests/integration/targets/inventory-v3.4/files/test-inventory-jinja2.json
tests/integration/targets/inventory-v3.4/files/test-inventory-legacy.json
tests/integration/targets/inventory-v3.4/files/test-inventory-noracks.json
tests/integration/targets/inventory-v3.4/files/test-inventory-options-flatten.json
tests/integration/targets/inventory-v3.4/files/test-inventory-options.json
tests/integration/targets/inventory-v3.4/files/test-inventory-plurals-flatten.json
tests/integration/targets/inventory-v3.4/files/test-inventory-plurals.json
tests/integration/targets/inventory-v3.4/files/test-inventory.json

#991
Fix: NetBox v3.4 test inventory
Tests for NetBox v3.4 have been failing because compare_inventory_json.py returning error that inventories do not match.
This PR fixes the issue.

Fix: NetBox v3.4 test inventory

---

plugins/modules/netbox_custom_field.py

Fixes #1018 
Add `datetime` as `type` in `netbox_custom_field`.
The `datetime` type that was added in NetBox 3.5 should be supported in this module as well.
Bring feature parity to the Ansible module.
The module doc was updated.
Feature: support datetime as custom_field type

netbox_custom_field: add datetime type

---

plugins/modules/netbox_cable.py
tests/integration/targets/v3.3/tasks/netbox_cable.yml
tests/integration/targets/v3.4/tasks/netbox_cable.yml
tests/integration/targets/v3.5/tasks/netbox_cable.yml

#1026 
It would be possible to include a tenant parameter when using the module, e.g.
```
tasks:
- name: Create cable within NetBox with only required information
netbox.netbox.netbox_cable:
netbox_url: http://netbox.local
netbox_token: thisIsMyToken
data:
tenant: tenant-slug
termination_a_type: dcim.interface
termination_a:
device: Test Nexus Child One
name: Ethernet2/2
termination_b_type: dcim.interface
termination_b:
device: Test Nexus Child One
name: Ethernet2/1
state: present
```
Currently rejected, "unsupported parameters for (netbox.netbox.netbox_cable) module: data.tenant."
Users of this module could set the tenant without resorting to the UI.
Parameter documentation should be included in PR.
add optional parameter tenant to netbox_cable

add tenant to netbox_cable

---

plugins/modules/netbox_power_port.py
plugins/modules/netbox_power_port_template.py

[Discussion 1047](https://github.com/netbox-community/ansible_modules/discussions/1047)
The power plugs support the newest options
...
Some options were not available
...
Newest options will be available
...
...
Add support for the newest options for power plugs and power plugs templates
...

Add missing power port options

---

docs/plugins/netbox_custom_field_module.rst
plugins/modules/netbox_custom_field.py
tests/integration/targets/v3.5/tasks/netbox_custom_field.yml

#1045 
This adds the `hidden-ifunset` option to the `ui_visibility` argument of the custom_fields module.
...
The current version of the custom_fields module does not allow users to create custom fields with their UI visibility set to "Hidden (if unset)" which is a valid option in the current version of NetBox.
...
- This change is backward-compatible.
- This change will allow users to make full use of the UI visibility options available in the current version of NetBox.
...
The docs have been updated in this file [docs/plugins/netbox_custom_field_module.rst](https://github.com/netbox-community/ansible_modules/compare/devel...aaron-iles:feature/1045-hidden-ifunset?expand=1#diff-5382d74858449f3904d8570b5bf117c7bf5c9d2bf356e3133cc7e9a3b636ea8a)
...
- Adds `hidden-ifunset` option to …

Adds hidden-ifunset option to ui_visibility argument of custom_fields

---

plugins/inventory/nb_inventory.py

#1052 
Fix schema caching to align with intended behavior: download only once per major NetBox version.
...
Schema caching is broken, i.e., re-fetches the (extremely large) schema on every playbook run.
...
The schema file is >6MB, so re-downloading it on every run is time-consuming, even on high performance networks.
...
No changes, as this is fixing intended behavior.
...
Fix API schema caching.
...

Closes #1052: Schema caching is broken

---

plugins/module_utils/netbox_utils.py
plugins/modules/netbox_device_type.py

Add the option default_platform on the device_type resource
The option is missing and does not allow the definition of the default platform
The platform will be able to be set by default and thus defining default configuration templates for a device for example. 
Add support for the default_plaform on device_type

feat: Add support for default_platform on device_types

---

plugins/lookup/nb_lookup.py
plugins/module_utils/netbox_utils.py
plugins/modules/netbox_power_port_template.py
tests/integration/targets/v3.5/tasks/netbox_power_port_template.yml
tests/integration/targets/v3.6/tasks/netbox_power_port_template.yml

No issue, context described below.
NetBox allows adding components (like power ports) to module types, not only to device types. This PR will address this.
Some users want to use module bays, hosting power supplies. This power supplies have a module type, which has power port templates. E.g: https://www.netbox.net/dcim/module-types/1/power-ports/
This PR adds `module_type`, which allows adding a power port to an existing module type in NetBox. Therefor one of `device_type` or `module_type` is required.
This PR adds a feature that is already implemented in the NetBox GUI, but missing in the Ansible collection/module. For example, the device library uses module types for PSU's: https://github.com/netbox-community/devicetype-library/blob/a7718d8d4b0a9d2f196166f5cbc4831bfb6be490/device-types/H …

Allow adding power port templates to modules

---

plugins/inventory/nb_inventory.py

Handle netbox api cache more gracefully

---

plugins/module_utils/netbox_dcim.py

When the `packaging` module is missing the error will be masked because we try to use `self.module` before it has been initialized
NA - 
This change make sure that the real error (missing `packaging` module) is not masked by an error arising from the use-before-initialization of the `self.module` attribute
The old behavior masked the error and made troubleshooting harder
NA
NA
Fixed use-before-initialization for `self.module`
* [X ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X] I have explained my PR according to the information in the comments or in a linked issue.
* [ X] My PR targets the `devel` branch.

Unmask "packaging module missing" error

---

plugins/modules/netbox_platform.py

This PR add support for the parameter `config_template` in platform entity
The option is not currently supported
> Add support for `config_template` in platform module

Feat: Support config_template opt in platform

---

plugins/inventory/nb_inventory.py

#1060
Allows Hosts to be sorted by their site's facility data.
Not possible.
Enables more options for sorting devices and objects depending on specific needs.
Included in change.
Adds "facility" option to group_by in nb_inventory plugin. This allows objects to be grouped by their site's facility data.

Add facility option to group_by in Inventory Plugin

---

plugins/inventory/nb_inventory.py

This allows storing secrets in config context data.
#551
This allows storing ansible-vault secrets in a NetBox config context, like this:
{
"plain_var": "value",
"secret_var": {
"__ansible_vault": "$ANSIBLE_VAULT;1.1;AES256\n123456…"
}
}
Currently encrypted values are returned as is, and cannot be used directly in Ansible playbooks or templates without the workaround described in #551.
The change should have no effect on existing installations; the workaround in #551 will still work but do nothing, as the values are now decrpyted earlier. Other possible workarounds (e.g. decrypting values in a playbook) might break if they expect an ansible-vault string.
Replacing `json.loads` with `self.loader.load` makes `nb_inventory` work more like [the builtin `script` …

Decrypt ansible-vault strings in nb_inventory

---

plugins/lookup/nb_lookup.py

- #370
- #376
In the `nb_lookup` plugin, when supplying multiple `id` fields to the `api_filter` parameter, it will return a list of items.
In the `nb_lookup` plugin, if we provide an `api_filter` containing the `id` field, it will use `.get()` instead of `.filter()`, thus returning the item instead of a list. See PR #376 for more information.
This is fine if you supply only one id. But let's say you want to get a list of items by ids?
For example: `id=1 id=5`
I would expect to get a list of 2 items. But at the moment, it will return the first item only.
This change adds a simple check to see if we're supplying multiple ids.
This fixes a bug where supplying multiple ids in the `api_filter` ends up returning only one item.
In fact, I'd even expect that supplying a single id would return a …

Fix bug in nb_lookup if api_filter contains multiple `id`

---

plugins/modules/netbox_rack_role.py
tests/integration/targets/v3.6/tasks/netbox_rack_role.yml

#1142 
Add the field `description` to `Rack Role`
The field `description` is not able to be used in `Rack Role`
`Benefit`: Users will now be able to use `description` in `Rack Role`
`Drawbacks`: None
`Backwards Compatible`: Yes
I believe the change is self-documenting. Let me know if I need to change something.
Add the field `description` to `Rack Role`

Add description to Rack Role

---

docs/plugins/netbox_vlan_module.rst
plugins/modules/netbox_vlan.py

#1137
Correct option name for vlan groups in docs.  No change to operation.
new behavior is the examples for vlan use the correct option name for vlan groups.
The benefit is a microscopic improvement in the documentation examples for creating VLANs
There are no known drawbacks.
This is a change to the docs, so ...
Corrected VLAN group option name in documentation.
* [X ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X] I have explained my PR according to the information in the comments or in a linked issue.
* [ X] My PR targets the `devel` branch.

vlan group option name is 'vlan_group' not 'group'

---

docs/requirements.txt
meta/runtime.yml
plugins/module_utils/netbox_utils.py
plugins/module_utils/netbox_virtualization.py
plugins/modules/netbox_circuit_type.py
plugins/modules/netbox_virtual_disk.py
tests/integration/targets/v3.7/tasks/main.yml
tests/integration/targets/v3.7/tasks/netbox_virtual_disk.yml

Add module to create disks for virtual machines.
New module

Add module netbox_virtual_disk

---

plugins/module_utils/netbox_ipam.py

This was uncovered by dependabot using a new version of ansible-core where I guess the sanity tests now check for unused imports.
https://github.com/netbox-community/ansible_modules/actions/runs/7515500523/job/20459479535

Remove unused imports

---

tests/integration/targets/v3.5/tasks/netbox_lookup.yml
tests/integration/targets/v3.6/tasks/netbox_lookup.yml
tests/integration/targets/v3.7/tasks/netbox_lookup.yml

Remove Jinja2 templating from conditionals

---

plugins/lookup/nb_lookup.py
plugins/module_utils/netbox_utils.py
plugins/module_utils/netbox_vpn.py
plugins/modules/netbox_l2vpn.py
plugins/modules/netbox_l2vpn_termination.py

#1149 
- Add support in nb_lookup for the netbox 3.7 `vpn.tunnel` and `vpn.tunnel_termination` objects.
- Depending on netbox version we are addressing, point the endpoints for `l2vpn` and `l2vpn_termination` to the correct app `ipam` or `vpn`
Fix `l2vpn` and `l2vpn_termination` support for netbox 3.7
Works against netbox 3.7 as well, which was broken because endpoint moved
...
...
...
...

Add new endpoints for vpn app

---

plugins/modules/netbox_device.py
plugins/modules/netbox_virtual_machine.py

Add config_template option on netbox_device and netbox_virtual_machine. Virtual machine is dependent on https://github.com/netbox-community/netbox/issues/15070

Add Config template to device and virtual machine

---

plugins/lookup/nb_lookup.py

Add endpoint in nb_lookup for the netbox 3.7 `virtualization.virtual-disks`
...
...
A simple change to permit to lookup the new virtual-disk objects.
...
...
...

Add new endpoints for Virtual Disk

---

tests/unit/module_utils/test_netbox_base_class.py

Calling `MagicMock.called_once`, `MagicMock.called_once_with`, or `MagicMock.not_called` returns a mock object and asserting that always succeeds.
Replace those calls with their correct `MagicMock.assert_*` counterparts.
Python 3.12 started to complain about it.
test: fix assertions for mock calls (for Python 3.12)

test: fix assertions for mock calls

---

plugins/inventory/nb_inventory.py

Add oob_ip documentation
Add the option to use the out of band IP as `ansible_host` instead of primary_ip.
There is no option to use the out of band ip currently
Allow users to use the new out of band ip option in their playbooks.
Also the query filter `has_oob_ip: True` is available. 
Add the ability to set out of band IP as ansible host.

Add out of band IP option

---

plugins/lookup/nb_lookup.py

#1185 
Since NetBox v3.6.0 there is an breaking change where the custom-fields and choices are split.
Currently there is no way to access the custom field choices when using NetBox v3.6.0 or higher
_Why do you think this project and the community will benefit from your proposed change?_
Starting from NetBox v3.6.0 it is not possible to use the lookup module to get the custom field choices.
_What are the drawbacks of this change?_
I do not know what happens when someone using it with an NetBox version lower than v3.6.0.
_Is it backwards-compatible?_
NetBox <v3.6.0; Use `custom-fields` to get the choices.
Netbox >v3.6.0; Use `custom-field-choice-sets`
...
Added `custom-field-choice-sets` to the lookup plugin.

Added custom-field-choice-sets to nb_lookup.py

---

docs/plugins/netbox_device_module.rst
plugins/modules/netbox_device.py
tests/integration/targets/v3.5/tasks/netbox_device.yml
tests/integration/targets/v3.6/tasks/netbox_device.yml
tests/integration/targets/v3.7/tasks/netbox_device.yml

Similarly, devices may occupy non-integer positions, such as 1.5, within a rack. Enabling float variables for position allows for accurate placement of devices at intermediate positions.
...
...
...
...
...

Change position type to float for netbox_device module

---

docs/plugins/netbox_device_type_module.rst
plugins/modules/netbox_device_type.py
plugins/modules/netbox_rack.py
tests/integration/targets/v3.5/tasks/netbox_device_type.yml
tests/integration/targets/v3.6/tasks/netbox_device_type.yml
tests/integration/targets/v3.7/tasks/netbox_device_type.yml

Some devices have a non-integer size, such as 1.5U, indicating that they occupy an intermediate space. Netbox accepts float variables, allowing for precise representation of these non-integer sizes.
...
...
...
...
...

Change u_height to float

---

docs/plugins/netbox_power_port_module.rst
plugins/modules/netbox_power_port.py

No related issues.
Added 'label' as a none required option to netbox_power_port module.
...
Possible to add  a label to a power port in NetBox.
...
We use NetBox in my organisation and I need to be able to create labels for powerports.
Since the option to add a label is optional it should not be a problem with backward compatibility.
...
Added a description of the label option in plugins/modules/netbox_power_port.py and generated a new version of
docs/plugins/netbox_power_port_module.rst.
...
...
* [ x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ x] I have explained my PR according to the information in the comments or in a linked issue.
* [ x] My PR targets the `devel` branch.

Added label to power port module

---

plugins/modules/netbox_export_template.py

#1213
Examples were for custom_link, not export_template.
Current examples are for custom_link, not export_template.
...
...
...

[Docs]: Provided examples for export_templates are for custom_link

---

plugins/inventory/nb_inventory.py

Related to https://github.com/netbox-community/ansible_modules/pull/1081
Makes `oob_ip` always available in the hostvars if it exists.
Not sure why we make `oob_ip` available only when `oob_ip_as_primary_ip` is set.
I believe there is value to access this property without altering `ansible_host`.
None
- `oob_ip` is now returned in hostvars if set
- Add the ability to set out of band IP as ansible host.

feat: make `oob_ip` available regardless of `oob_ip_as_primary_ip`

---

plugins/inventory/nb_inventory.py
tests/unit/inventory/test_data/extract_custom_fields/data.json
tests/unit/inventory/test_nb_inventory.py

Only extract custom fields that are set. Netbox supports having non-required custom fields, and we don't want to set variables when the custom fields are not set in Netbox. This is particularly valuable if you are using flatten_custom_fields=True.
Custom fields that are not set in Netbox will be respected and not set in the Ansible module (e.g., they won't overwrite the variable if it's already set).
When flatten_custom_fields=False, the custom fields which are unset will be excluded from the custom_fields dictionary. I don't think this will cause any issues.
...
Unset custom fields, in combination with `flatten_custom_fields=True`, will no longer overwrite host variables.

Dont extract null values from custom fields (nb_inventory)

---

plugins/modules/netbox_power_outlet.py

There are no open related issues.
Added label to the poweroutlet module.
...
Possible to add a label to a poweroutlets in NetBox.
...
We use NetBox in my organisation and I need to create labels for poweroutlets.
Since the option to add a label is optional it should not be a problem with backward compatibility.
I did test it in NetBox v3.5.9 
...
Added a description of the label option in plugins/modules/netbox_power_outlets.py 
...
...
* [ x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ x] I have explained my PR according to the information in the comments or in a linked issue.
* [ x] My PR targets the `devel` branch.

added label to poweroutlet

---

plugins/module_utils/netbox_utils.py

add ALLOWED_QUERY_PARAMS module_bay by device
When adding a module, module bays are not uniquely identifiable by name only.
none
none
add ALLOWED_QUERY_PARAMS module_bay by device

add ALLOWED_QUERY_PARAMS module_bay by device

---

plugins/modules/netbox_power_outlet_template.py

#1229
Ability to use power outlet of type iec-60320-c21 with power outlet templates.
...
Power outlet type iec-60320-c21 is supporter by NetBox but is missing from the power outlet templates module.
...
...
...
Added power outlet type iec-60320-c21 to netbox_power_outlet_template module.
...
* [ x] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ x] I have explained my PR according to the information in the comments or in a linked issue.
* [ x] My PR targets the `devel` branch.

added power outlet type iec-60320-c21 to template

---

.github/workflows/main.yml
plugins/modules/netbox_custom_field.py
plugins/modules/netbox_custom_link.py
plugins/modules/netbox_export_template.py
tests/integration/targets/v4.0/tasks/netbox_custom_field.yml
tests/integration/targets/v4.0/tasks/netbox_custom_link.yml
tests/integration/targets/v4.0/tasks/netbox_export_template.yml

Modules adjusted:
- netbox_custom_field
- netbox_custom_link
- netbox_export_template
Added the option object_types as NetBox 4.0 changed content_types to object_types.

Adjust modules for NetBox 4.0 support

---

plugins/module_utils/netbox_utils.py

#1233 
Allow more query parameters to parent_location

Extend query param for parent_location

---

.ansible-lint-ignore
CHANGELOG.rst
changelogs/changelog.yaml

Fix #1256: Igore YAML indentation on changelog yaml file

---

changelogs/fragments/1281_move_prefix_lookup_to_secondary.yml
plugins/inventory/nb_inventory.py

If fetch_all is false, prefix lookup depends on site lookup, so move it
to secondary lookup.
Solves #733

fix: move prefix lookup to lookup secondary

---

changelogs/fragments/1273-ability-to-rename-host-inventory-vars.yml
plugins/inventory/nb_inventory.py
tests/unit/inventory/test_nb_inventory.py

None.
Certain environments may have conflicts with the variables given by Netbox, and the variables used in the existing Ansible codebase.
With this change, such cases can be worked around by renaming individual variables, or whole groups of them.
For example, this will rename all `cluster*` variables to have a `netbox__` prefix instead (e.g., `cluster_group` -> `netbox__cluster_group`):
```yaml
rename_variables:
- pattern: 'cluster(.*)'
repl: 'netbox__cluster\1'
```
Uses a list, instead of a dict, to ensure that the order of evaluation is strictly defined across all Python versions, and to add the ability to exclude certain variables from being rewritten. For example:
```yaml
rename_variables:
- pattern: 'cluster_type'
repl: 'cluster_type'
- pattern: 'cluster(.*)'
repl: …
```

Add ability to rename host inventory variables using patterns

---

changelogs/fragments/fix_issues_1279_1280.yml
plugins/modules/netbox_location.py

This commit adds the `status` and `facility` options to the `netbox_location` module. The `status` option allows specifying the status of the location, while the `facility` option allows specifying the data center provider or facility. These options were added to enhance the functionality of the module and provide more flexibility in managing locations within NetBox.
Fixes #1279, #1280
#1279, #1280
Adds the `status` and `facility` options to the `netbox_location` module. The `status` option allows specifying the status of the location, while the `facility` (added in NetBox v4.0.0) option allows specifying the data center provider or facility. These options were added to enhance the functionality of the module and provide more flexibility in managing locations within NetBox. 
...
Currently …

feat: Add `status` and `facility` options to `netbox_location` module

---

changelogs/fragments/1276-feature-netbox_cluster_group-adds-description-field.yml
plugins/modules/netbox_cluster_group.py

Add `description` option to `netbox_cluster_group` module, allowing users to specify the description of the cluster group. 
#1276 
The `netbox_cluster_group` module now supports the `description` option, allowing users to specify the description of the cluster group.
...
The `netbox_cluster_group` module was missing the `description` option.
...
This allows users to specify the description of the cluster group. This enhancement provides more flexibility in managing cluster groups within NetBox.
...
The new option is added in the documentation part of the file.
...
Add support for the `description` option for the `netbox_cluster_group` module.
...

feat: Add `description` option to `netbox_cluster_group` module

---

plugins/inventory/nb_inventory.py

#833
Regards the Netbox Inventory plugin.   
Resolves `KeyError: 'site'` when a caching plugin is used and `prefixes: true`
Currently, any time the cache is read, and there are prefixes in the cache, Ansible crashes on a missing 'site' key. This is because the site key is removed from the prefix before storing it in cache. After the fix, the site key is only deleted when it actually exists.
Without this change it seems impossible to use an Ansible inventory caching plugin ánd enable `prefixes` in the Netbox inventory plugin.
Two years ago @endreszabo [stated that](https://github.com/netbox-community/ansible_modules/issues/833#issue-1377946354) making this change resulted in an empty `prefixes: []` array for any given site for him. When I try to reproduce this I don't get that problem, and …

Prevent 'site' key error when using inventory caching

---

changelogs/fragments/1307-feature-netbox_vlan_group-add-vid_ranges.yml
plugins/modules/netbox_vlan_group.py

#1307
Add possibility to add and update vid_ranges in VLAN Group
Possibility to use the new field in NetBox v4.1.0
The user can make changes to vid_ranges on VLAN groups in NetBox v4.1.0
The old fields are not removed 
The user need to know which field to use based on the version on NetBox
...
minor_changes:
- Add `vid_ranges` to `netbox_vlan_group` module (https://github.com/netbox-community/ansible_modules/issues/1307)
* [ X] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ X] I have explained my PR according to the information in the comments or in a linked issue.
* [ X] My PR targets the `devel` branch.

Add vid_ranges to netbox_vlan_group

---

changelogs/fragments/1327-add-custom-headers.yml
plugins/inventory/nb_inventory.py
plugins/lookup/nb_lookup.py

#896
This PR adds the ability to add custom headers to the API requests for both the inventory and lookup module. It supports headers in the module arguments, or as an environment variable in JSON format.
Currently there is no ability to add custom headers to API requests.
Custom headers are required for many deployments behind reverse proxies for additional authentication tokens or cookies. This only adds new compatibility and is fully backwards compatible.
Docstrings are updated
Add support for custom headers

Custom Header Support

---

changelogs/fragments/1335-api-status-page-not-found.yml
plugins/inventory/nb_inventory.py

#1335 
Fix call /api/status/ instead /api/status. Path without trailing slash produce django warning.
...
...
Yes. Is it backwards-compatible.
...
...
Fix call /api/status/ instead /api/status in nb_inventory plugin. (https://github.com/netbox-community/ansible_modules/issues/1335).
...

fix issue 1335

---

changelogs/fragments/1339-name-to-fhrp-group.yml
plugins/modules/netbox_fhrp_group.py

Add name as option to netbox_fhrp_group.

Fix issue #1339

---

plugins/modules/netbox_permission.py

According to https://netboxlabs.com/docs/netbox/en/stable/administration/permissions/, constraints can be either a dictionary or a list of dictionaries. The only way to represent this in Ansible is with the `raw` type.
#1373 
Update the constraint field type from `list` to `raw`.
There is no way to specify multiple constraints without this change. There is also no way to specify the type more precisely, at least according to https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#argument-spec
I believe the generated docs will need to be regenerated, but no manual changes are required.
Update type of permission constraint from `list` to `raw`

Set type of permission constraint to raw

---

changelogs/fragments/action_groups_config_template.yml
meta/runtime.yml

netbox_config_template is now working
Fix missing netbox_config_template module in module_defaults

Fix missing netbox_config_template module in module_defaults

---

plugins/inventory/nb_inventory.py

This fixes a bug where `sites` doesn't contain the prefixes list when using NetBox >= 4.2.0, due to breaking changes in the datamodel (https://github.com/netbox-community/netbox/releases/tag/v4.2.0)
> - The `site` foreign key field on `ipam.Prefix` has been replaced by the `scope` generic foreign key.
- No drawbacks, as compatibility with older NetBox versions is maintained

fix: Add prefixes to site for NetBox >=4.2

---

changelogs/fragments/netbox_circuit_termination.yml
plugins/modules/netbox_circuit_termination.py

#1401 
This fix is to resolve the changes created by the [NetBox 4.2.0 release](https://github.com/netbox-community/netbox/releases/tag/v4.2.0) relating to:
`The site and provider_network foreign key fields on circuits.CircuitTermination have been replaced by the termination generic foreign key.`
Current behavior results in module failure with the error:
`A circuit termination must attach to a terminating object.`
This fix resolves the issue with NetBox 4.2.x.  It is backward compatible with prior versions.
Documentation in the module has been updated.
Updated netbox_circuit_termination.py to support NetBox 4.2.x breaking changes.
* [ x ] I have read the comments and followed the [CONTRIBUTING.md](https://github.com/netbox-community/ansible_modules/blob/devel/CONTRIBUTING.md).
* [ x ] I …

Updated netbox_circuit_termination.py to support NetBox 4.2.x

---

changelogs/fragments/nb_inventory.yml
plugins/inventory/nb_inventory.py

#1408 
Updated Plugin to parse the full path of the netbox server and compose API endpoints accordingly.
...
This is a patch I originally made for v3.13 which had updated parsing of the openapi endpoint and assumes that netbox is always running in the root context rather than a path.     This performs the additional url parsing to derive the correct inventory API endpoints if netbox is running on a path rather than a root context.
I've tested this rebased patch on latest netbox running on in the root context path, as well as my legacy deployment running on host.com/netbox/
...
- allows users to run in additional supported configurations ex: somehost.example.com/netbox/ rather than only netbox.example.com
-
...
...
update inventory plugin to support netbox API running on non-root context …

inventory plugin: support netbox endpoints running in a non-root context path (subpath)

---

changelogs/fragments/netbox_tag.yml
plugins/modules/netbox_tag.py
tests/integration/targets/v4.2/tasks/netbox_tag.yml

Not tracked yet: Setting object type for tags is not supported.
Add extra parameters to the module so object_types is supported.
N/A
Support for this field
...
- Suport for "object_types" in netbox_tag

Support of object types for netbox_tag module

---

plugins/lookup/nb_lookup.py

Add possibility to query mac-addresses with the nb_lookup plugin for NetBox 4.2+
...
Feature is missing so far
...
- mac-addresses was added in Netbox 4.2 so we need to follow the feature set
- No drawbacks
- The mac-addresses feature wasn't available in Netbox versions lower than 4.2 so it won't impact those.
...
n/a
...
nb_lookup plugin - Allow mac-addresses lookup
...

fix: nb_lookup plugin: Allow mac-addresses lookup

---

changelogs/fragments/1435-fix-duplicate-task-name.yml
docs/plugins/netbox_device_type_module.rst
docs/plugins/netbox_platform_module.rst
docs/plugins/netbox_prefix_module.rst
plugins/modules/netbox_device_type.py
plugins/modules/netbox_platform.py
plugins/modules/netbox_prefix.py

As mentionned in https://github.com/netbox-community/ansible_modules/pull/1433#issuecomment-3024601330 I fix lint issue
N/A
N/A
Lint check will pass
Name of tasks
Fix Lint error caused by duplicate task name

Fix duplicate task name in documentation

---

docs/getting_started/how-to-use/advanced.rst

#1466 
Fix the hyperlink + typo

docs: Small typo + hyperlink on advanced.rst

---

changelogs/fragments/1469-fix-old-apis.yml
plugins/inventory/nb_inventory.py

…
#1469  
The variable that is being used to identify the api endpoint can now be used in the code path for older netbox servers so the inventory plugin shouldn't crash when attempting to communicate with old servers.
...
When using old netbox servers we should be able to retrieve inventory information rather than crashing with errors about not being able to access variables.
...
This is only relevant to old old servers but we currently have a broken code path in the current version of the plugin.
One alternative in my mind would be to remove all of the checks for version lt 3.5.0, update the documentation to indicate that it's really not supported and probably create a new check for the old api version/path that just returns an error saying "upgrade to a newer version of netbox"
...
None …

Fix #1469 - the old api code path didnt get the variable defined that  is being used to locate the api endpoints
